//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountService.EDServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EDServiceReference.EncryptDecryptServices")]
    public interface EncryptDecryptServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptServices/encryptString", ReplyAction="http://tempuri.org/EncryptDecryptServices/encryptStringResponse")]
        string encryptString(string plainString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptServices/encryptString", ReplyAction="http://tempuri.org/EncryptDecryptServices/encryptStringResponse")]
        System.Threading.Tasks.Task<string> encryptStringAsync(string plainString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptServices/decryptString", ReplyAction="http://tempuri.org/EncryptDecryptServices/decryptStringResponse")]
        string decryptString(string encryptString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptServices/decryptString", ReplyAction="http://tempuri.org/EncryptDecryptServices/decryptStringResponse")]
        System.Threading.Tasks.Task<string> decryptStringAsync(string encryptString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EncryptDecryptServicesChannel : AccountService.EDServiceReference.EncryptDecryptServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncryptDecryptServicesClient : System.ServiceModel.ClientBase<AccountService.EDServiceReference.EncryptDecryptServices>, AccountService.EDServiceReference.EncryptDecryptServices {
        
        public EncryptDecryptServicesClient() {
        }
        
        public EncryptDecryptServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncryptDecryptServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptDecryptServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptDecryptServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string encryptString(string plainString) {
            return base.Channel.encryptString(plainString);
        }
        
        public System.Threading.Tasks.Task<string> encryptStringAsync(string plainString) {
            return base.Channel.encryptStringAsync(plainString);
        }
        
        public string decryptString(string encryptString) {
            return base.Channel.decryptString(encryptString);
        }
        
        public System.Threading.Tasks.Task<string> decryptStringAsync(string encryptString) {
            return base.Channel.decryptStringAsync(encryptString);
        }
    }
}
